In [1]:
import pandas as pd

In [2]:
data_og = pd.read_excel('reto.xlsx', sheet_name='protocolos_produccion', skiprows = 1)
data_og.head()

,indice_lote,Estación,Fecha,Hora,Tipo,Producción\nAcumulada x1000,PreC VM\n[kN],CPVM\n[kN],Srel\n[%],n,...,Srel\n[%].1,n.1,VM\n[mm],Srel\n[%].2,n.2,VM\n[kp],Srel\n[%].3,n.3,VM\n[mm].1,Srel\n[%].4
0,32,1.0,2023-06-19,22:02:05,M,22,2.16,24.90,6.0,10,...,1.09,10,5.58,0.60,10,11.9,5.71,10,21.01,0.05
1,32,1.0,2023-06-19,22:06:16,M,43,2.76,26.93,6.6,10,...,1.27,10,5.61,0.56,10,11.8,6.36,10,21.01,0.06
2,32,1.0,2023-06-19,22:28:45,M,157,2.88,26.26,6.4,10,...,1.21,10,5.60,0.55,10,11.3,7.48,10,21.01,0.02
3,32,1.0,2023-06-19,23:42:56,M,426,3.73,29.76,6.6,10,...,0.98,10,5.65,0.44,10,11.9,7.12,10,21.02,0.11
4,32,1.0,2023-06-20,00:02:29,M,530,3.07,25.94,6.3,10,...,0.93,10,5.62,0.47,10,12.0,5.54,10,21.01,0.02

In [3]:
data = data_og.copy()

In [4]:
# Seleccion de datos numericos
data.drop(columns=['Fecha', 'Hora', 'Tipo'], inplace = True)

In [10]:
# Calculo de la media de los valores por lote
df2 = data.groupby(['indice_lote', 'Estación']).mean()
df2.head()

                      Producción\nAcumulada x1000  PreC VM\n[kN]  CPVM\n[kN]  \
indice_lote Estación
1           1.0                        411.700000       4.331000   26.535000
            2.0                        413.700000       6.276000   32.511000
2           1.0                        398.888889       4.761111   31.504444
            2.0                        396.111111       5.404444   35.926667
3           1.0                        369.727273       5.900000   28.095455

                      Srel\n[%]          n     VM\n[mg]   Mín\n[mg]  \
indice_lote Estación
1           1.0        7.120000  81.000000  1002.310000  981.220000
            2.0        6.860000  81.000000  1002.260000  979.100000
2           1.0        5.711111  80.000000   999.211111  984.500000
            2.0        5.988889  80.000000   995.144444  978.666667
3           1.0        5.563636  81.818182   996.881818  981.745455

                        Máx\n[mg]  Srel\n[%].1        n.1  VM\n[mm]  \
indice_lote Estación
1           1.0       1022.610000     1.007000  81.000000  5.654000
            2.0       1020.210000     1.070000  81.000000  5.658000
2           1.0       1023.255556     0.844444  80.000000  5.623333
            2.0       1017.577778     0.890000  80.000000  5.616667
3           1.0       1016.536364     0.741818  81.818182  5.642727

                      Srel\n[%].2        n.2  VM\n[kp]  Srel\n[%].3  \
indice_lote Estación
1           1.0          0.600000  81.000000  6.590000    11.863000
            2.0          0.658000  81.000000  6.310000    12.949000
2           1.0          0.477778  80.000000  6.244444    11.953333
            2.0          0.562222  80.000000  6.500000    12.758889
3           1.0          0.412727  81.818182  7.200000    10.570000

                            n.3  VM\n[mm].1  Srel\n[%].4
indice_lote Estación
1           1.0       81.000000   21.110000     0.030000
            2.0       81.000000   21.110000     0.019000
2           1.0       80.000000   21.100000     0.034444
            2.0       80.000000   21.098889     0.027778
3           1.0       81.818182   21.120000     0.031818

In [11]:
# Importación de df friabilidad
df_friab = pd.read_excel('reto.xlsx', sheet_name='calidad_friabilidad')
df_friab.head()

   indice_lote  Friabilidad (%)
0           32           0.0028
1           33           0.0025
2           46           0.0038
3           47           0.0038
4           49           0.0029

In [12]:
# Merge df base y df friabilidad
df = df2.merge(df_friab, how = 'left', on = 'indice_lote')
df

,indice_lote,Producción\nAcumulada x1000,PreC VM\n[kN],CPVM\n[kN],Srel\n[%],n,VM\n[mg],Mín\n[mg],Máx\n[mg],Srel\n[%].1,n.1,VM\n[mm],Srel\n[%].2,n.2,VM\n[kp],Srel\n[%].3,n.3,VM\n[mm].1,Srel\n[%].4,Friabilidad (%)
0,1,411.700000,4.331000,26.535000,7.120000,81.000000,1002.310000,981.220000,1022.610000,1.007000,81.000000,5.654000,0.600000,81.000000,6.590000,11.863000,81.000000,21.110000,0.030000,0.0025
1,1,413.700000,6.276000,32.511000,6.860000,81.000000,1002.260000,979.100000,1020.210000,1.070000,81.000000,5.658000,0.658000,81.000000,6.310000,12.949000,81.000000,21.110000,0.019000,0.0025
2,2,398.888889,4.761111,31.504444,5.711111,80.000000,999.211111,984.500000,1023.255556,0.844444,80.000000,5.623333,0.477778,80.000000,6.244444,11.953333,80.000000,21.100000,0.034444,0.0038
3,2,396.111111,5.404444,35.926667,5.988889,80.000000,995.144444,978.666667,1017.577778,0.890000,80.000000,5.616667,0.562222,80.000000,6.500000,12.758889,80.000000,21.098889,0.027778,0.0038
4,3,369.727273,5.900000,28.095455,5.563636,81.818182,996.881818,981.745455,1016.536364,0.741818,81.818182,5.642727,0.412727,81.818182,7.200000,10.570000,81.818182,21.120000,0.031818,0.0047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,52,442.666667,4.487778,27.471111,5.644444,17.777778,995.922222,981.000000,1006.700000,0.797778,17.777778,5.581111,0.491111,17.777778,12.611111,4.592222,17.777778,21.107778,0.060000,0.0046
101,53,414.888889,4.271111,30.525556,5.200000,17.777778,998.711111,980.433333,1010.400000,0.898889,17.777778,5.613333,0.446667,17.777778,13.255556,5.940000,17.777778,21.108889,0.034444,0.0037
102,53,416.777778,4.980000,29.955556,5.833333,17.777778,1000.922222,985.888889,1010.177778,0.784444,17.777778,5.597778,0.463333,17.777778,13.188889,4.773333,17.777778,21.101111,0.035556,0.0037
103,55,338.642857,4.071429,49.064286,5.950000,24.000000,1001.821429,981.178571,1023.164286,1.165000,24.000000,5.585714,1.121429,24.000000,8.592857,13.604286,24.000000,21.065714,0.055714,0.0025
104,56,502.500000,3.627778,48.611111,6.572222,45.333333,1002.672222,982.005556,1021.650000,1.007778,45.333333,5.637222,1.042222,45.333333,8.411111,12.996111,45.333333,21.036667,0.063333,0.0036